package com.example.canteen.service.data;

/** Contains the authorization token data generated by the server. */
public class AuthToken {
    public final String token;

    public AuthToken(String token) {
        this.token = token;
    }
}
